# Generated by Django 3.0.4 on 2020-04-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0002_auto_20200411_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='month',
            field=models.CharField(choices=[('1', 'April 2020'), ('2', 'May 2020'), ('3', 'June 2020'), ('4', 'July 2020'), ('5', 'August 2020'), ('6', 'September 2020'), ('7', 'October 2020'), ('8', 'November 2020'), ('9', 'December 2020'), ('10', 'January 2021'), ('11', 'February 2021'), ('12', 'March 2021')], default='1', max_length=20),
        ),
    ]
