# Generated by Django 3.0.4 on 2020-04-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0007_auto_20200413_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
