# Generated by Django 3.0.4 on 2020-04-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0008_category_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
    ]
